### DISCUSSION TITLE
Deploy Worklenz to production using Docker or Docker compose, plus setup Nginx for frontend

### DISCUSSION THREAD

**Discussion by Jacger** [Worklenz/worklenz#40] [Q&A] [answered]
Hi guys, Can you guys help me deploy Worklenz on production environment using docker or docker-compose? I cloned the project but the documentation only shows Worklenz setup running on Development environment.

If it's really good, can you guide me to configure Nginx, because after building frontend, the proxy-docker.config.json file will not work anymore.

Many thanks.

**Comment by kalinga777** [comment]
@chamikaJ - would you like to assist?

**Reply by Jacger** [reply]
Yes, could you help me, I got stuck, thank you

**Comment by Jacger** [comment]
@chamikaJ 
Could you help me, I got stuck, thank you

The thing i want:
- Request from frontend can reach backend
- Socket can work properly
- The version of project after deploy is Production

=======================================================================================

I did the following steps:
- [x]  Setup Postgresql (version 15)
- [x]  Build frontend
- [x]  Build backend
- [x]  Using nginx to redirect client request to frontend and backend

=======================================================================================

What I got stuck:
- Suppose I have a domain `mypage.com`, should I set the frontend and backend domains the same (`mypage.com`)?
- With the domain `mypage.com`, how should I replace the domain appropriately in the .env file?
- Can I have the nginx config?
- Socket got stuck

=======================================================================================

I use docker-compose to run application:
<details>
<summary>`docker-compose.yml` file:</summary>

```yaml
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_started
      frontend:
        condition: service_started

  frontend:
    build:
      context: ./worklenz-frontend
      dockerfile: Dockerfile
    container_name: worklenz_frontend
    depends_on:
      backend:
        condition: service_started

  backend:
    build:
      context: ./worklenz-backend
      dockerfile: Dockerfile
    container_name: worklenz_backend
    environment:
      - NODE_ENV=development
      - PORT=3000
      - SESSION_NAME=worklenz.sid
      - SESSION_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - COOKIE_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - SOCKET_IO_CORS=http://frontend:4200
      - SERVER_CORS=*
      - DB_USER=worklenz_backend
      - DB_PASSWORD=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - DB_NAME=worklenz_db
      - DB_HOST=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - DB_PORT=5432
      - DB_MAX_CLIENTS=50
      - GOOGLE_CLIENT_ID=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - GOOGLE_CLIENT_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - GOOGLE_CALLBACK_URL="http://backend:3000/api/secure/google/verify"
      - LOGIN_FAILURE_REDIRECT="/"
      - LOGIN_SUCCESS_REDIRECT="http://frontend:4200/auth/authenticate"
      - ANGULAR_DIST_DIR="../worklenz_frontend/dist/worklenz"
      - ANGULAR_SRC_DIR="../worklenz_frontend"
      - BACKEND_PUBLIC_DIR="../worklenz_backend/src/public"
      - BACKEND_VIEWS_DIR="../worklenz_backend/src/views/admin"
      - COMMIT_BUILD_IMMEDIATELY=true
      - HOSTNAME=frontend:4200
      - USE_PG_NATIVE=true
      - JWT_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - MAIL_HOST=smtp.gmail.com
      - MAIL_USER=system@wap-jmg.co.jp
      - MAIL_PASSWORD=fred nwhw bidr cbsw
      - MAIL_FROM=system@wap-jmg.co.jp
      - REGION="us-west-2"
      - BUCKET="BUCKET_NAME_HERE"
      - S3_URL="S3_URL_HERE"
      - S3_ACCESS_KEY_ID="S3_ACCESS_KEY_ID_HERE"
      - S3_SECRET_ACCESS_KEY="S3_SECRET_ACCESS_KEY_HERE"
      - AWS_REGION="us-west-2"
      - AWS_ACCESS_KEY_ID="AWS_ACCESS_KEY_ID_HERE"
      - AWS_SECRET_ACCESS_KEY="AWS_SECRET_ACCESS_KEY_HERE"
```
</details>

<details>
<summary>`Dockerfile.yml` of nginx:</summary>

```yaml
FROM nginx:1.25.2-alpine

COPY conf.d /etc/nginx/conf.d
```

`default.conf` config file in folder `conf.d`:
```yml
server {
  listen 80;
  server_name localhost;

  client_max_body_size 150M;
  client_body_buffer_size 16K;

  location / {
    proxy_pass http://frontend:80;
  }

  location /socket {
    proxy_pass http://backend:3000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }

  location /api {
    proxy_pass http://backend:3000;
  }

  location /secure {
    proxy_pass http://backend:3000;
  }
}
```
</details>


<details>
<summary>`Dockerfile.yml` of frontend:</summary>

```yaml
# Stage 1: Build the Angular app
FROM node:18-alpine3.17 AS build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Serve the Angular app using nginx
FROM nginx:1.25.2-alpine
COPY default.conf /etc/nginx/conf.d/
COPY --from=build /app/dist/worklenz /usr/share/nginx/html
EXPOSE 80
```
</details>

<details>
<summary>`Dockerfile.yml` of Backend:</summary>

```yaml
# Stage 1: Build the Angular app
###################
# BUILD
###################
# Use the official Node.js 18 image as a base
FROM node:18 AS build

# Create and set the working directory
WORKDIR /usr/src/app

# Install global dependencies
RUN npm install -g ts-node typescript grunt grunt-cli

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install app dependencies
RUN npm ci

# Copy the rest of the application code
COPY . .

# Run the build script to compile TypeScript to JavaScript
RUN npm run build

###################
# RELEASE
###################

FROM node:18 AS production

USER node

WORKDIR /app

# Copy the bundled code from the build stage to the production image
COPY --chown=node:node --from=build /usr/src/app/worklenz-email-templates ./worklenz-email-templates
COPY --chown=node:node --from=build /usr/src/app/node_modules ./node_modules
COPY --chown=node:node --from=build /usr/src/app/build ./build
COPY --chown=node:node --from=build /usr/src/app/release ./
COPY --chown=node:node --from=build /usr/src/app/package.json ./

# Expose the port the app runs on
EXPOSE 3000

# Start the application
CMD [ "npm", "start" ]
```
</details>
