### ISSUE TITLE
The service is inaccessible

### ISSUE THREAD

**Issue by Lks7** [Worklenz/worklenz#167]
Hi dev.
When I start up with docker everything works fine, but when I access the service address, the browser tells me that the request to access localhost was rejected
You are not authorized to view this page.
Here's my relevant configuration info:
```
services:
  frontend:
    build:
      context: ./worklenz-frontend
      dockerfile: Dockerfile
    container_name: worklenz_frontend
    ports:
      - "5000:5000"
    depends_on:
      backend:
        condition: service_started
    env_file:
      - ./worklenz-frontend/.env.production
    networks:
      - worklenz

  backend:
    build:
      context: ./worklenz-backend
      dockerfile: Dockerfile
    container_name: worklenz_backend
    ports:
      - "3005:3005"
    env_file:
      - ./worklenz-backend/.env  
    networks:
      - worklenz


networks:
  worklenz:
```
.env
```
# Server
NODE_ENV=production
PORT=3005
SESSION_NAME=worklenz.sid
SESSION_SECRET="a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6"
COOKIE_SECRET="a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6"

# CORS
SOCKET_IO_CORS=http://localhost:5000
SERVER_CORS=*

# Database - 
DB_USER=
DB_PASSWORD=
DB_NAME=worklenz_db          
DB_HOST=host.docker.internal  
DB_PORT=5432                  
DB_MAX_CLIENTS=50

# STORAGE - 
STORAGE_PROVIDER=s3
AWS_REGION=us-east-1          # MinIO默认区域
AWS_ACCESS_KEY_ID=# MinIO默认访问密钥
AWS_SECRET_ACCESS_KEY=# MinIO默认秘密密钥
AWS_BUCKET=worklenz   # 存储桶名称
S3_URL=http://host.docker.internal:9000  # 关键修改：指向本地MinIO

# 保持其他配置不变...
# (复制原.env文件中的其他配置到这里)


# HOST
HOSTNAME=localhost:5000

# SLACK
#SLACK_WEBHOOK=your_slack_webhook_url
#USE_PG_NATIVE=false

# JWT SECRET
#JWT_SECRET=your_jwt_secret

# FRONTEND_URL
FRONTEND_URL=http://localhost:5000

CONTACT_US_EMAIL=

# Email Cronjobs
#ENABLE_EMAIL_CRONJOBS=true

GOOGLE_CLIENT_ID="your_google_client_id"
GOOGLE_CLIENT_SECRET="your_google_client_secret"
```
log：

![Image](https://github.com/user-attachments/assets/0a067b89-1ec2-4d57-bad9-f0104efddddc)
Browser alert message:

![Image](https://github.com/user-attachments/assets/4f13d76f-965f-4a36-b746-d4e9819c1ce8)

**Comment by kithmina1999** [comment]
@Lks7  Have you created an .env.production for frontend or if you already have, did you change the backend url to your adjusted port number?

**Comment by Lks7** [comment]
@kithmina1999  It still doesn't work I've switched to the other way around, thanks for the reply

**Comment by Lks7** [comment]
@kithmina1999 
After reading your reply I made another attempt and now I solved the problem!!!!
I hypothesized that the reason was that port 5000 was occupied in my environment, so I switched to port 5200.
And it's important to change only the port of the local environment, the container's port still needs to be 5000, or else I'll be prompted that the service isn't started
Where I modified it:
```
  frontend:
    build:
      context: ./worklenz-frontend
      dockerfile: Dockerfile
    container_name: worklenz_frontend
    ports:
      - "5200:5000" -- this change
    env_file:
      - ./worklenz-frontend/.env.production
    networks:
      - worklenz

```
