### ISSUE TITLE
Unable to Self-Host with Docker-Compose

### ISSUE THREAD

**Issue by Codename-11** [Worklenz/worklenz#58]
Hello 😁!

I'm very interested in using Worklenz. I've looked into alternatives, including Plane, and while both look promising, Worklenz seems to align more with my team. 

I've attempted many times to follow both the github, issues, and the latest blog post from Dec 2 "Worklenz Docker Guide", all to no avail. I attempted with a minimal environment definition via docker-compose, and as well by copying the .env.template to .env in the root of ./worklenz-backend - which doesn't seem to help.

I'm able to access the web interface, but continue reciving 500 Internal Server errors when attempting to create an account. My intention is to use this local only - no need for Google OAuth, etc.

When checking the docker compose logs:
`[webpack-dev-server] [HPM] Error occurred while proxying request tgi-http.tgi.local:4200/secure/verify to http://backend:3000/ [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)`

`2024-12-04 14:43:55.117 UTC [465] FATAL:  role "worklenz_client" does not exist`

[env.txt](https://github.com/user-attachments/files/18009978/env.txt)
[docker-compose.txt](https://github.com/user-attachments/files/18009986/docker-compose.txt)

Is there any definitive solution? My general experience with a dockerized application would imply only needing to modify the environment/.env and compose file to get the app up and running. Please let me know if there's any advice! 😁

**Comment by Codename-11** [comment]
I did make some progress. I was able to get rid of the error for the role "worklenz_client" by modifying the `backend 6_user-permission.sql` file.

I still recieve the error that the proxy request cannot communicate with the backend.

Oddly enough, from within the frontend container, I can ping `db` but not `backend`....

**Comment by chamikaJ** [comment]
@Codename-11 Could you please try adding the following section at the end of your docker-compose.yml file and see if it resolves the issue?
```

networks:
  worklenz:

```

**Comment by Codename-11** [comment]
I appreciate the reply!

As you can see in the originally attached docker-compose.txt (attached again)
[docker-compose.txt](https://github.com/user-attachments/files/18062861/docker-compose.txt)

I already have the `worklenz` network defined 😊

**Comment by kithmina1999** [comment]
Error  seems to occured because frontend unable to connect with backend check whether you have backend running and  role "worklenz_client" does not exist error happens because of the problem in the db 
you havn't defined db_user properly try suing environment variables instead adding direct values
```
POSTGRES_DB: "${DB_NAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}"]
```

**Comment by Codename-11** [comment]
I'll try my hand using environment variables as suggested and report back. I appreciate the assistance of course! 😁

**Comment by kalinga777** [comment]
> I'll try my hand using environment variables as suggested and report back. I appreciate the assistance of course! 😁

Is this fixed

**Comment by ilovefreesw** [comment]
> > I'll try my hand using environment variables as suggested and report back. I appreciate the assistance of course! 😁
> 
> Is this fixed ?

No it is not. The current compose file is invalid.

**Comment by kithmina1999** [comment]
> No it is not. The current compose file is invalid.

try this docker compose file

```
services:
  frontend:
    image: ghcr.io/worklenz/worklenz-frontend
    build:
      context: ./worklenz-frontend
      dockerfile: Dockerfile
    container_name: worklenz_frontend
    ports:
      - "4200:4200"
    depends_on:
      backend:
        condition: service_started
    networks:
      - worklenz

  backend:
    image: ghcr.io/worklenz/worklenz-backend
    build:
      context: ./worklenz-backend
      dockerfile: Dockerfile
    container_name: worklenz_backend
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ANGULAR_DIST_DIR
      - ANGULAR_SRC_DIR
      - AWS_REGION
      - BACKEND_PUBLIC_DIR
      - BACKEND_VIEWS_DIR
      - COMMIT_BUILD_IMMEDIATELY
      - COOKIE_SECRET
      - DB_HOST=${DB_HOST}
      - DB_MAX_CLIENTS
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - GOOGLE_CALLBACK_URL
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - HOSTNAME
      - LOGIN_FAILURE_REDIRECT
      - NODE_ENV
      - PORT
      - SESSION_NAME
      - SESSION_SECRET
      - SLACK_WEBHOOK
      - SOCKET_IO_CORS
      - SOURCE_EMAIL
      - USE_PG_NATIVE
      - BUCKET
      - REGION
      - S3_URL
      - S3_ACCESS_KEY_ID
      - S3_SECRET_ACCESS_KEY
    networks:
      - worklenz

  db:
    image: postgres:15
    container_name: worklenz_db
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - worklenz
    volumes:
      - worklenz_postgres_data:/var/lib/postgresql/data
      - ./worklenz-backend/database/:/docker-entrypoint-initdb.d

volumes:
  worklenz_postgres_data:

networks:
  worklenz:

```
